version: '3'

services:
  postgres-db:
    # docker hub 에서 에떤 버전이 있는지 확인 가능
    image: postgres:17
    container_name: local_postgres
    # 데이터베이스 id, password 등 설정
    environment:
      POSTGRES_USER: discodeit_user
      POSTGRES_PASSWORD: discodeit1234
      POSTGRES_DB: discodeit
      TZ: Asia/Seoul
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    # 데이터 영속성을 위한 설정
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: